jx/modules/cluster/main.tf

```
node_count - (Optional) The number of nodes per instance group. This field can be used to update the number of nodes per instance group but should not be used alongside autoscaling.
```
https://www.terraform.io/docs/providers/google/r/container_node_pool.html#node_count

fix: removed node_count from autoscaling pool

---

jx/modules/cluster/main.tf

**NOTE: this _could_ possibly trigger terraform to recreate the node pool**

fix: set the initial_node_count for the node pool

---

modules/dns/main.tf

We need to always create cert-manager and exdns namespaces and service accounts
since the current boot pipeline will always apply the underlying Helm charts.
If a namespace or service account does not exist before running `jx boot` it will
be created as part of `helm apply`. Once it is created by Helm, one cannot go
back to Terraform and enable DNS there, since Terraform will not be able to create
the already existing resources.
fixes #72

fix: always create DNS related namespaces

---

README.md
main.tf

Since https://github.com/terraform-providers/terraform-provider-google/issues/4276#issuecomment-612987189 looks to be resolved as mentioned here https://github.com/jenkins-x/terraform-google-jx/issues/71. It seems fitting to remove the google provider constraint and allow users the flexibility to specify the constraint (_if one is required_).
If users feel they need to lock down the google provider versions, they could specify the provider versions when using the jx module:
```yaml
provider "google" {	
version = "~> 2.12.0"	
project = var.gcp_project	
zone    = var.zone	
}	
provider "google-beta" {	
version = "~> 2.12.0"	
project = var.gcp_project	
zone    = var.zone	
}
```

feat: remove google provider constraints

---

README.md

The generated jx-requirments.yml should only be used on initial `jx boot`
fixes #74

fix: adding note to README about use of jx-requirements.yml

---

main.tf

This widens the version scope for all providers required by this module whilst maintaining the minimum required version. If there exists a version that affects the implementation of this module, then perhaps a maximum version constraint should be considered for the provider in question.
Fixes https://github.com/jenkins-x/terraform-google-jx/issues/88

fix: widen version scope for all providers

---

examples/additional-nodepool/main.tf

As discussed, an example showing how you can easily extend the default configuration with additional node pools, without having to throw away or modify the jx module.

chore: add example for additional node pools

---

README.md
examples/additional-nodepool/main.tf
main.tf
modules/backup/variables.tf
modules/cluster/main.tf
modules/cluster/variables.tf
modules/vault/variables.tf
output.tf
scripts/ci.sh
spec/k8s_spec.sh
variables.tf

- deprecated var.zone in a backwards-compatible manner in favour of var.location
fixes #78
This makes the location configuration of the cluster more flexible and allows for example for zonal vs regional clusters.

feat: allow to specify cluster location as zone or region

---

README.md
main.tf
modules/backup/main.tf
modules/backup/variables.tf
modules/cluster/storage.tf
modules/cluster/variables.tf
modules/vault/main.tf
modules/vault/variables.tf
variables.tf

Introducing a _bucket_location_ variable to specify the storage location for generated buckets. ATM, it is using the default _US_.
fixes #66

feat: allow configuration of bucket location via bucket_location variable

---

README.md
main.tf
modules/gsm/main.tf
modules/gsm/outputs.tf
modules/gsm/variables.tf
output.tf
variables.tf

- vault is still enabled by default
- this enables the secrets manager API service, creates a GCP service account and related rolebindings.
- not supported on JX2
fixes: #131

feat: optionally add support for enabling google secrets manager rather than vault, but keep vault as the default

---

modules/cluster/variables.tf

This change adds some of the machine types that were missing from `machine_types_cpu` and `machine_types_memory` maps.
Note that I intentionally omitted the `e2-micro`, `e2-small`, etc as these use burstable resources and it's unclear what effect this would have on the k8s resource allocations.

chore: add latest machine types from GCP docs

---

main.tf

Fix manually verified with project generated from [jx3-gitops-repositories/jx3-terraform-gke](https://github.com/jx3-gitops-repositories/jx3-terraform-gke) by updating `main.tf` with the following source URL:
```
module "jx" {
source                          = "github.com/haysclark/terraform-google-jx?ref=fix%2Fkubernetes-provider"
```
PR resolves #173

fix: limit kubernetes provider to ~>1.11.0

---

modules/cluster/main.tf

This fixes oauth scopes not being set for the autoscaled pool that got introduced in #106
Background:
the auto scaled pool has different oauth scopes (the default ones) than the clusters default pool.
Default pool:
Auto scaled pool: 
Presumably this also causes the issue described in #169
Fix:
The same oauth permissions are applied both to the clusters default pool and the autoscale pool using the `auto_provisioning_defaults` in the `cluster_autoscaling` block: https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#oauth_scopes
This consistently restores oauth scopes across both pools to the state pre #106 
Note:
The long term solution to this, according to googles and terraforms documentation, would be setting a non-default service account with …

fix: define oauth scopes for the autoscaled nodepool

---

README.md
main.tf
modules/cluster/main.tf
modules/cluster/variables.tf
variables.tf

When I try to create my jx cluster in an existing vpc, `terraform apply` fails with the error
```
Network "mynetwork" requires specifying a subnetwork
```
This change allows me to create the jx cluster in my existing vpc.

feat: optional cluster_subnetwork configuration

---

main.tf

The right solution would be to go through all the breaking changes documented here: https://github.com/hashicorp/terraform-provider-google/releases/tag/v4.0.0 and here: https://github.com/hashicorp/terraform-provider-google-beta/releases/tag/v4.0.0
and ensure that the module works after fixing all the breaking changes.
For now, it is safe/better to restrict it to less than 4.0.0 for both google and google-beta provider.
fixes #209

fix: restrict google provider to less than 4.0.0 for now

---

modules/jx-boot/vault.tf

This was already done for the AWS module.

fix: upgrade vault charts to support kubernetes 1.21+

---

Makefile
OWNERS
main.tf
modules/cluster/main.tf
modules/cluster/variables.tf
modules/vault/main.tf
variables.tf

```
Warning: Version constraints inside provider configuration blocks are deprecated
--
  |   |   |   | │
  |   |   |   | │   on .terraform/modules/jx/main.tf line 15, in provider "google":
  |   |   |   | │   15:   version = ">= 3.46.0, < 4.0.0"
  |   |   |   | │
  |   |   |   | │ Terraform 0.13 and earlier allowed provider version constraints inside the
  |   |   |   | │ provider configuration block, but that is now deprecated and will be
  |   |   |   | │ removed in a future version of Terraform. To silence this warning, move the
  |   |   |   | │ provider version constraint into the required_providers block.
  |   |   |   | │ (and 7 more similar warnings elsewhere)
```

fix: remove versions from provider block

---

main.tf
modules/cluster/main.tf
modules/cluster/variables.tf
variables.tf

Seperated terraform variables for min/max nodes because the node pool and the cluster used same variables previously, changing the node pool would change the cluster initial node count causing the recreation of the cluster.
Plus added autoscaler location policy
initial_cluster_node_count = var.initial_cluster_node_count
initial_primary_node_pool_node_count = var.initial_primary_node_pool_node_count
autoscaler_min_node_count    = var.autoscaler_min_node_count
autoscaler_max_node_count    = var.autoscaler_max_node_count

Seperated terraform variables for min/max nodes

---

README.md
main.tf
modules/cluster/main.tf
modules/cluster/variables.tf
variables.tf

Beginning with Terraform's Google provider version 5.0.0+, container clusters deletion protection defaults to `true` which prevents the` terraform destroy` command from deleting the cluster.  To provide a mechanism for overriding this protection, a new TF variable `delete_protect` is introduced and will be used to set the `deletion_protection` attribute for the `google_container_cluster` resource.
https://github.com/jenkins-x/terraform-google-jx/issues/233
You must explicitly set `deletion_protection=false` (and run `terraform apply` to write the field to state) in order to destroy a cluster. It is recommended to not set this field (or set it to true) until you're ready to destroy.

fix: allow cluster deletion (terraform-google-jx#233)

---

.terraform-docs.yml
CONTRIBUTING.md
Makefile
README.md

terraform-docs v0.12 added support for --output-file which can be used
alongside --output-mode inject to in-place update the content inside a
target file (e.g. README.md).
This also adds '.terraform-docs.yml' file for better user experience and
consistency across team members.

chore: update terraform-docs to in-place update README
