- main.tf
fixes: https://github.com/jenkins-x/terraform-google-jx/issues/40
> fix: issue with 400 Bad Request errors

- README.md
- main.tf
- output.tf
- variables.tf
> fix: using random pet name to chose cluster name if not explicitly set

- main.tf
> fix: making sure to use right variable for path to template file

- README.md
- main.tf
- modules/backup/main.tf
- modules/backup/variables.tf
- modules/cluster/main.tf
- modules/cluster/serviceaccount.tf
- modules/cluster/variables.tf
- modules/dns/main.tf
- modules/dns/variables.tf
- modules/vault/main.tf
- modules/vault/variables.tf
- output.tf
- scripts/ci.sh
- spec/k8s_spec.sh
- variables.tf
> fix: adding resource_labels variable to allow creation of cluster labels

- README.md
- main.tf
- modules/cluster/storage.tf
- modules/jx-requirements.yml.tpl
- output.tf
- scripts/ci.sh
- spec/jx_requirements_spec.sh
- variables.tf
> fix: always render ingress section in jx-requirements.yml

- OWNERS
- README.md
- examples/backend-encrypted/main.tf
- examples/backend/main.tf
- examples/basic/main.tf
- adding documentation around GOOGLE_APPLICATION_CREDENTIALS
fixes #39
fixes #62
> fix: adding examples and documentation for state management

- main.tf
Fixes https://github.com/jenkins-x/terraform-google-jx/issues/84
> fix: widen version scope for local provider

- README.md
- main.tf
- modules/cluster/main.tf
- modules/cluster/variables.tf
- variables.tf
> feat: allow the configuration of the GKE release channel

- README.md
- main.tf
- modules/backup/main.tf
- modules/backup/outputs.tf
- modules/backup/variables.tf
- modules/jx-requirements.yml.tpl
- scripts/ci.sh
- variables.tf
> feat: make resource creation for backup/velero optional

- README.md
- main.tf
- modules/jx-requirements.yml.tpl
- modules/vault/main.tf
- modules/vault/outputs.tf
- modules/vault/variables.tf
- variables.tf
- making sure that in the case of external Vault instance, no unnecessary GCloud resources get created
fixes #104
> feat: introducing vault_url variable to configure external Jenkins X system Vault

- README.md
- main.tf
- modules/cluster/main.tf
- modules/cluster/variables.tf
- variables.tf
Should be fairly straightforward. I was interested in making the nodes use SSD storage.
> Allow specifying disk type

- modules/cluster/main.tf
- modules/cluster/serviceaccount.tf
- modules/cluster/variables.tf
> feat: use cluster autoscaler to improve deploy time

- README.md
- examples/backend-encrypted/main.tf
- examples/backend/main.tf
- examples/basic/main.tf
> fix: making sure usage examples specifiy the jx_requirements output

- README.md
- main.tf
- modules/cluster/serviceaccount.tf
- modules/cluster/variables.tf
- scripts/ci.sh
- spec/gcloud_spec.sh
- spec/k8s_spec.sh
- variables.tf
> feat: adding GCP and Kubernetes service accounts for JX UI

- main.tf
> feat: enable Kubernetes Engine API

- modules/cluster/outputs.tf
- modules/vault/main.tf
> fix: check if tuples are empty

- .gitignore
- Makefile
- examples/additional-nodepool/main.tf
- examples/basic/main.tf
- modules/backup/main.tf
- modules/backup/outputs.tf
- modules/backup/variables.tf
- modules/cluster/main.tf
- modules/cluster/serviceaccount.tf
- modules/cluster/storage.tf
- modules/cluster/variables.tf
- modules/dns/main.tf
- modules/dns/variables.tf
- modules/vault/outputs.tf
- modules/vault/variables.tf
> fix: add recursive flag to terraform fmt

- OWNERS
> chore: add ankitm123 and MarckK to the OWNERS file

- README.md
- examples/preemptible/main.tf
- main.tf
- variables.tf
> feat: Add support for preemptible node

- main.tf
- modules/backup/main.tf
- modules/backup/variables.tf
- modules/dns/main.tf
fixes #136 
Not sure about some of the other resources that are getting created, for example: `google_service_account_iam_member`. If the service account wont get created, should this resource get created, seems like no to me.
> fix: disable namespace and sa creation for jx3

- modules/cluster/variables.tf
> feat: disable legacy auth by default

- modules/cluster/serviceaccount.tf
- modules/cluster/variables.tf
- spec/gcloud_spec.sh
- spec/k8s_spec.sh
now that the CloudBees jxui app is deprecated
> fix: use the pipeline visualizer service account

- README.md
- jenkins-x.yml
- main.tf
- modules/dns/main.tf
- modules/dns/variables.tf
- modules/jx-requirements.yml.tpl
- scripts/ci.sh
- variables.tf
Related PR: https://github.com/jx3-gitops-repositories/jx3-terraform-gke/pull/30
Related [slack thread](https://kubernetes.slack.com/archives/C9LTHT2BB/p1607443301111500)
More coherent with the TLS doc and the other gitops templates.
> fix(terraform): add apex_domain* variables and deprecate parent_domain* variables

- main.tf
> fix: roll back the change to the template

- modules/dns/variables.tf
- variables.tf
Just bring this inline with the other description as this one is incomplete.
> chore: fix apex_domain_integration_enabled variable description

- modules/cluster/main.tf
After looking into an issue where node pools allowed 0-1000 nodes I found
that the initial autoscaling feature added autoscaling node pools rather than nodes.
I've created a cluster with this config and am going to monitor progress.
> refactor: replace autoscale nodepool with autoscale nodes

- .gitignore
- modules/cluster/main.tf
> fix: flip conditionals for installing kuberhealthy

- README.md
- examples/private-nodes/main.tf
- main.tf
- modules/cluster/firewall.tf
- modules/cluster/main.tf
- modules/cluster/variables.tf
- variables.tf
i believe this is the smallest change-set to enable private cluster creation. closes #162
> feat: optional minimal private cluster configuration

- .terraform.lock.hcl
- main.tf
- modules/backup/main.tf
- modules/cluster/main.tf
- modules/cluster/serviceaccount.tf
- modules/dns/main.tf
- modules/gsm/main.tf
- modules/vault/main.tf
> feat: upgrade gcp tf provider to 4+

- README.md
- main.tf
- modules/cluster/main.tf
- modules/cluster/variables.tf
- variables.tf
> fix: add option to enable spot instances

- README.md
- main.tf
- modules/cluster/main.tf
- modules/cluster/variables.tf
- variables.tf
Added option to opt out of primary node pool, so that you can deploy your own node pool with custom configuration
> Added option to opt out of primary nodepool
